import { Injectable } from '@angular/core';

export interface Project {
  id: number;
  title: string;
  client?: string;
  year?: string;
  description: string;
  category: 'Web' | 'Mobile' | 'Design' | 'AI';
  technologies: string[];
  imageUrl: string;
  challenge?: string;
  solution?: string;
  outcome?: string;
}

export interface BlogPost {
  id: number;
  title: string;
  excerpt: string;
  content?: string; // HTML string for body
  date: string;
  category: string;
  readTime: string;
  imageUrl: string;
  author?: string;
}

@Injectable({
  providedIn: 'root'
})
export class DataService {

  private projects: Project[] = [
      {
        id: 1,
        title: 'Nexus E-Commerce',
        client: 'Nexus Retail Group',
        year: '2023',
        description: 'A full-scale e-commerce platform featuring real-time inventory management, AI-driven product recommendations, and a seamless checkout experience.',
        category: 'Web',
        technologies: ['Angular', 'Node.js', 'Stripe', 'Tailwind'],
        // ID 201: Blurry tech/lights - Artistic
        imageUrl: 'https://picsum.photos/id/201/800/600',
        challenge: 'Nexus needed to migrate from a legacy monolithic system to a microservices architecture without disrupting their 50k daily active users. The main pain points were slow page loads (3s+) and a rigid CMS that made marketing campaigns difficult to launch.',
        solution: 'We architected a headless solution using Angular for the storefront and Node.js for the backend services. We implemented a redis caching layer to handle high-traffic product queries and integrated a builder.io CMS for marketing flexibility.',
        outcome: 'Page load times dropped to 0.8s, conversion rates increased by 15% in the first quarter, and the marketing team can now launch campaigns in minutes rather than days.'
      },
      {
        id: 2,
        title: 'FitTrack Pro',
        client: 'HealthCorp Inc.',
        year: '2023',
        description: 'Mobile application for tracking fitness goals, visualizing workout progress, and connecting with personal trainers.',
        category: 'Mobile',
        technologies: ['Flutter', 'Firebase', 'Dart'],
        // ID 73: Abstract shapes/puzzle - Represents structure/body
        imageUrl: 'https://picsum.photos/id/73/800/600',
        challenge: 'Users were abandoning existing fitness apps due to complex data entry and lack of visual progress indicators. The client wanted a "zero-friction" logging experience.',
        solution: 'We utilized Flutter to create a buttery-smooth cross-platform experience. We implemented custom gesture controls for logging sets and reps, and used D3.js (via WebView) for complex but intuitive progress charts.',
        outcome: 'The app achieved a 4.8-star rating on the App Store and was featured in "Apps We Love". User retention at day-30 is 40% higher than the industry average.'
      },
      {
        id: 3,
        title: 'Golden Hour Branding',
        client: 'Golden Hour Luxury',
        year: '2022',
        description: 'Complete brand identity design including logo, typography, and marketing assets for a luxury lifestyle brand.',
        category: 'Design',
        technologies: ['Figma', 'Illustrator', 'Motion'],
        // ID 250: Camera/Photography - Artistic
        imageUrl: 'https://picsum.photos/id/250/800/600',
        challenge: 'A new luxury lifestyle brand needed an identity that felt timeless yet modern, avoiding the clichéd minimalist aesthetic of competitors.',
        solution: 'We developed a visual language based on the warmth of the "golden hour" sun. This involved a custom serif typeface, a warm, earthy color palette, and a photography direction that emphasized natural light and texture.',
        outcome: 'The brand launch was a massive success, with the visual identity being cited by Vogue as "refreshingly warm and inviting".'
      },
      {
        id: 4,
        title: 'Vision AI Dashboard',
        client: 'SafeCity Tech',
        year: '2022',
        description: 'Analytics dashboard leveraging computer vision to analyze retail foot traffic and customer sentiment in real-time.',
        category: 'AI',
        technologies: ['Python', 'TensorFlow', 'Angular', 'D3.js'],
        // ID 870: Lighthouse/Moody - Represents vision/guidance
        imageUrl: 'https://picsum.photos/id/870/800/600',
        challenge: 'Retailers have cameras but no data. They needed a way to visualize terabytes of video data in real-time to understand customer behavior.',
        solution: 'We built a high-performance Angular dashboard that consumes WebSocket streams from the Python/TensorFlow backend. We used WebGL for rendering heatmaps of foot traffic over store layouts.',
        outcome: 'Pilot stores saw a 10% increase in sales by optimizing product placement based on the heatmaps generated by our dashboard.'
      },
      {
        id: 5,
        title: 'EcoHome Smart Hub',
        client: 'GreenLiving',
        year: '2021',
        description: 'IoT interface for managing smart home devices with energy optimization algorithms.',
        category: 'Web',
        technologies: ['React', 'GraphQL', 'AWS IoT'],
        // ID 338: Coffee/Table - Warm interior vibe
        imageUrl: 'https://picsum.photos/id/338/800/600',
        challenge: 'Connecting devices from different manufacturers (Zigbee, Z-Wave, WiFi) into a single, cohesive interface that non-tech-savvy users could understand.',
        solution: 'We created a unified GraphQL API to abstract the device differences. The UI focused on "Scenes" rather than devices, allowing users to control their home based on context (e.g., "Movie Night", "Away").',
        outcome: 'Reduced customer support calls by 60% due to the intuitive interface design.'
      },
      {
        id: 6,
        title: 'FinTech Vault',
        client: 'SecureBank',
        year: '2021',
        description: 'Secure banking application with biometric authentication and blockchain-based transaction verification.',
        category: 'Mobile',
        technologies: ['Swift', 'Kotlin', 'Blockchain'],
        // ID 449: City blur/Motion - Fintech/Speed
        imageUrl: 'https://picsum.photos/id/449/800/600',
        challenge: 'Building a banking app that felt as secure as a vault but as easy to use as a social media app.',
        solution: 'We implemented a hybrid security model using on-device biometrics and server-side behavioral analysis. The UI used subtle animations to confirm security actions, giving users peace of mind.',
        outcome: 'Acquired 100k users in the first 6 months with zero security breaches reported.'
      }
    ];

  private blogPosts: BlogPost[] = [
      {
        id: 1,
        title: 'The Future of Angular: What v18+ Brings',
        excerpt: 'Exploring the new zoneless change detection, signal-based inputs, and how they revolutionize performance.',
        content: `<p>Angular has long been criticized for its reliance on Zone.js, a library that monkey-patches browser APIs to trigger change detection. While effective, it added overhead and made debugging stack traces a nightmare.</p><p>With the introduction of Signals and Zoneless change detection, Angular is entering a new era of performance. Signals provide a reactive primitive that allows the framework to know exactly <em>what</em> changed and <em>where</em>, rather than checking the entire component tree.</p><h3>Why Signals Matter</h3><p>Signals are not just a state management tool; they are the backbone of a fine-grained reactivity system. By adopting signals, we can drop Zone.js entirely, reducing bundle size and improving runtime performance significantly.</p>`,
        date: 'Oct 12, 2023',
        category: 'Development',
        readTime: '5 min read',
        // ID 1: Computer/Laptop - clean
        imageUrl: 'https://picsum.photos/id/1/800/400',
        author: 'Meet Joshi'
      },
      {
        id: 2,
        title: 'Mastering Material Design 3',
        excerpt: 'A deep dive into the tonal palettes, dynamic color systems, and elevation guides of MD3.',
        content: `<p>Material Design 3 (or Material You) is Google's most expressive design system to date. It moves away from the rigid, shadow-heavy interfaces of MD2 towards a more organic, colorful, and flat aesthetic.</p><p>One of the key features is the dynamic color system, which extracts a color scheme from the user's wallpaper. This creates a deeply personal connection between the user and the app.</p><h3>Elevation & Layout</h3><p>MD3 replaces shadows with surface tonal variations to indicate elevation. This "surface-tint" approach is much subtler and works better in both light and dark modes.</p>`,
        date: 'Sep 28, 2023',
        category: 'Design',
        readTime: '7 min read',
        // ID 106: Flowers/Vibrant - Colors for Material Design
        imageUrl: 'https://picsum.photos/id/106/800/400',
        author: 'Meet Joshi'
      },
      {
        id: 3,
        title: 'AI-Driven UX Patterns',
        excerpt: 'How generative AI is changing user expectations and the way we design interface interactions.',
        content: `<p>Generative AI is not just a backend technology; it's a UX paradigm shift. Users no longer want to filter and search; they want to <em>ask</em> and <em>receive</em>.</p><p>We are seeing a move from imperative UI (clicking buttons to do things) to declarative UI (describing what you want). This requires designers to think less about layouts and more about conversation flows and intent recognition.</p>`,
        date: 'Aug 15, 2023',
        category: 'AI',
        readTime: '4 min read',
        // ID 532: Abstract Geometry - AI/Complexity
        imageUrl: 'https://picsum.photos/id/532/800/400',
        author: 'Meet Joshi'
      },
      {
        id: 4,
        title: 'Scaling Node.js Applications',
        excerpt: 'Best practices for microservices architecture and handling high concurrency in Node backends.',
        content: `<p>Node.js is single-threaded, which makes it excellent for I/O bound tasks but challenging for CPU-intensive operations. Scaling requires a solid understanding of the event loop and clustering.</p><h3>The Microservices Approach</h3><p>Breaking a monolith into microservices allows you to scale individual components independently. For example, your image processing service might need 10 instances while your user profile service only needs 2.</p>`,
        date: 'Jul 04, 2023',
        category: 'Backend',
        readTime: '6 min read',
        // ID 48: Dark tech - Server/Structure
        imageUrl: 'https://picsum.photos/id/48/800/400',
        author: 'Meet Joshi'
      }
    ];

  getProjects(): Project[] {
    return this.projects;
  }

  getProjectById(id: number): Project | undefined {
    return this.projects.find(p => p.id === id);
  }

  getBlogPosts(): BlogPost[] {
    return this.blogPosts;
  }

  getBlogPostById(id: number): BlogPost | undefined {
    return this.blogPosts.find(p => p.id === id);
  }
}